package com.yunho.convention.value

object Dependency {
    const val ANDROIDX_CORE_KTX = "androidx-core-ktx"
    const val ANDROIDX_ACTIVITY_COMPOSE = "androidx-activity-compose"
    const val ANDROIDX_COMPOSE_BOM = "androidx-compose-bom"
    const val ANDROIDX_COMPOSE_UI = "androidx-compose-ui"
    const val ANDROIDX_COMPOSE_UI_TOOLING_PREVIEW = "androidx-compose-ui-tooling-preview"
    const val ANDROIDX_COMPOSE_MATERIAL3 = "androidx-compose-material3"
    const val ANDROIDX_NAVIGATION_COMPOSE = "androidx-navigation-compose"
    const val ANDROIDX_HILT_NAVIGATION_COMPOSE = "androidx-hilt-navigation-compose"
    const val ANDROIDX_DATASTORE_CORE = "androidx-datastore-core"
    const val ANDROIDX_DATASTORE_PREFERENCES_CORE = "androidx-datastore-preferences-core"
    const val UI_GRAPHICS = "ui-graphics"
    const val LIFECYCLE_RUNTIME_COMPOSE = "lifecycle-runtime-compose"
    const val HILT_ANDROID = "hilt-android"
    const val HILT_COMPILER = "hilt-compiler"
    const val RETROFIT_CORE = "retrofit-core"
    const val RETROFIT_KOTLIN_SERIALIZATION = "retrofit-kotlin-serialization"
    const val RETROFIT_CONVERTER_GSON = "retrofit-converter-gson"
    const val KOTLINX_COLLECTIONS_IMMUTABLE = "kotlinx-collections-immutable"
    const val GSON = "gson"
    const val RX_ANDROID = "rx-android"
    const val RX_KOTLIN = "rx-kotlin"
    const val JUNIT4 = "junit4"
    const val JUNIT = "junit"
    const val ANDROIDX_TEST_ESPRESSO_CORE = "androidx-test-espresso-core"
    const val APPCOMPAT = "appcompat"
    const val MATERIAL = "material"
    const val KOTPREF = "kotPref"
    const val KOTPREF_ENUMS = "kotPref-enumSupport"
    const val ORBIT_COMPOSE = "orbit-compose"
    const val ORBIT_VIEWMODEL = "orbit-viewmodel"
}
